async(page)=>{
  page.setDefaultTimeout(10000);const checks=[];const assert=(ok,label)=>{if(!ok)throw new Error(label);checks.push(label);};
  if(await page.locator('#settings').isVisible())await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.getByRole('button',{name:'主页设置',exact:true}).click();
  await page.locator('[data-tab="reset"]').click();
  await page.getByRole('button',{name:'重置主页',exact:true}).click();
  await page.getByRole('button',{name:'确认',exact:true}).click();
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.getByRole('button',{name:'添加分组',exact:true}).click();
  await page.getByRole('textbox',{name:'分组名称'}).fill('验收分组');
  await page.locator('#group-form').getByRole('button',{name:'保存',exact:true}).click();
  await page.locator('.sidebar-group').getByText('验收分组',{exact:true}).waitFor();
  assert(await page.locator('.sidebar-group.active').textContent()==='验收分组','新分组创建后激活');
  await page.getByRole('button',{name:'主页',exact:true}).click();
  await page.locator('#grid .site-tile[aria-label="淘宝"]').click({button:'right'});
  await page.getByRole('button',{name:'移动到分组 / 文件夹',exact:true}).click();
  await page.getByRole('combobox').selectOption({label:'验收分组'});
  await page.getByRole('button',{name:'移动',exact:true}).click();
  await page.locator('#modal').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'验收分组',exact:true}).click();
  assert(await page.getByRole('button',{name:'淘宝',exact:true}).count()===1,'网站可以移动到其他分组');
  await page.getByRole('button',{name:'主页',exact:true}).click();
  await page.getByRole('button',{name:'文件夹',exact:true}).click();
  assert(await page.locator('.folder-grid>button').count()===3,'文件夹可展开并显示子网站');
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390px 主页无横向页面溢出');
  await page.screenshot({path:'output/playwright/mobile-home.png'});
  await page.getByRole('button',{name:'主页设置',exact:true}).click();
  assert(Math.round((await page.locator('#settings').boundingBox()).width)===390,'窄屏设置抽屉适配屏幕');
  await page.locator('[data-tab="wallpaper"]').click();
  await page.screenshot({path:'output/playwright/mobile-settings.png'});
  assert(await page.evaluate(()=>{const d=document.querySelector('.settings-content');return d.scrollWidth<=d.clientWidth+1;}),'窄屏设置内容无横向溢出');
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.setViewportSize({width:1440,height:900});
  await page.getByRole('button',{name:'主页设置',exact:true}).click();
  await page.locator('[data-tab="reset"]').click();
  await page.getByRole('button',{name:'重置主页',exact:true}).click();
  await page.getByRole('button',{name:'确认',exact:true}).click();
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.reload();await page.getByRole('button',{name:'天气',exact:true}).waitFor();
  await page.waitForTimeout(800);
  await page.screenshot({path:'output/playwright/replica-home.png'});
  await page.getByRole('button',{name:'主页设置',exact:true}).click();
  await page.screenshot({path:'output/playwright/replica-settings.png'});
  await page.locator('[data-tab="backup"]').last().click();
  await page.screenshot({path:'output/playwright/replica-backup.png'});
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  return{checks};
}
