async (page) => {
  page.setDefaultTimeout(10000);
  const checks=[];
  const assert=(condition,label)=>{if(!condition)throw new Error(label);checks.push(label);};
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.context().route('https://example.com/**',route=>route.fulfill({status:200,contentType:'text/html',body:'<title>Search destination</title>'}));
  if(await page.locator('#modal').isVisible())await page.getByRole('button',{name:'关闭',exact:true}).click();
  if(await page.locator('#settings').isVisible())await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.getByRole('button',{name:'主页设置',exact:true}).click();
  await page.locator('[data-tab="reset"]').click();
  await page.getByRole('button',{name:'重置主页',exact:true}).click();
  await page.getByRole('button',{name:'确认',exact:true}).click();
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.waitForTimeout(250);
  assert(await page.getByRole('button',{name:/PDF|AiPPT|AI免费生成PPT/i}).count()===0,'默认主页无 PDF 与 AiPPT 入口');
  const metrics=await page.evaluate(()=>Object.fromEntries(['#clock','#search','#grid'].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return[s,{x:r.x,y:r.y,width:r.width,height:r.height}];})));
  assert(Math.abs(metrics['#search'].width-600)<1&&Math.abs(metrics['#grid'].x-105)<1,'搜索栏 600px、网格左边距 105px 与原版对齐');
  await page.screenshot({path:'output/playwright/replica-home.png'});
  await page.getByRole('button',{name:'主页设置',exact:true}).click();
  assert(Math.round((await page.locator('#settings').boundingBox()).width)===450,'设置为 450px 右侧抽屉');
  await page.screenshot({path:'output/playwright/replica-settings.png'});
  await page.getByRole('slider',{name:'图标大小',exact:true}).fill('72');
  assert(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--icon-size'))==='72px','图标大小即时预览');
  await page.locator('[data-tab="open"]').click();
  await page.getByRole('switch',{name:'新标签页打开搜索结果',exact:true}).uncheck();
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'主页设置',exact:true}).click();
  assert(await page.getByRole('slider',{name:'图标大小',exact:true}).inputValue()==='72','图标设置刷新后保留');
  await page.getByRole('slider',{name:'图标大小',exact:true}).fill('60');
  await page.locator('[data-tab="open"]').click();
  assert(!(await page.getByRole('switch',{name:'新标签页打开搜索结果',exact:true}).isChecked()),'打开方式刷新后保留');
  await page.getByRole('switch',{name:'新标签页打开搜索结果',exact:true}).check();
  await page.locator('[data-tab="search"]').click();
  await page.getByRole('switch',{name:'搜索历史',exact:false}).check();
  await page.getByRole('button',{name:'＋ 添加搜索引擎',exact:true}).click();
  await page.getByRole('textbox',{name:'名称',exact:true}).fill('验收搜索');
  await page.getByRole('textbox',{name:'搜索地址',exact:true}).fill('https://example.com/?q={query}');
  await page.locator('#engine-form').getByRole('button',{name:'添加',exact:true}).click();
  await page.locator('.engine-settings').getByText('验收搜索',{exact:true}).waitFor();
  assert(await page.locator('.engine-settings').getByText('验收搜索',{exact:true}).count()===1,'可以添加自定义搜索引擎');
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.getByRole('button',{name:'切换搜索引擎',exact:true}).click();
  await page.locator('.engine-picker').getByRole('button',{name:'验 验收搜索',exact:false}).click();
  await page.getByRole('searchbox',{name:'搜索内容'}).fill('中文 & 空格');
  const popupPromise=page.waitForEvent('popup');
  await page.getByRole('button',{name:'搜索',exact:true}).click();
  const popup=await popupPromise;
  await popup.waitForLoadState('domcontentloaded');
  assert(decodeURIComponent(popup.url().split('?q=')[1])==='中文 & 空格','搜索在新标签页打开并正确编码中文');
  await popup.close();
  await page.getByRole('searchbox',{name:'搜索内容'}).fill('');
  await page.getByRole('searchbox',{name:'搜索内容'}).focus();
  assert(await page.locator('#search-panel').getByText('中文 & 空格',{exact:true}).count()===1,'搜索历史可回显');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'添加图标',exact:true}).click();
  await page.getByRole('button',{name:'添加网址',exact:false}).click();
  await page.getByRole('textbox',{name:'名称',exact:true}).fill('验收网站');
  await page.getByRole('textbox',{name:'网址',exact:true}).fill('example.com');
  await page.locator('#site-form').getByRole('button',{name:'保存',exact:true}).click();
  await page.getByRole('button',{name:'验收网站',exact:true}).waitFor();
  assert(await page.getByRole('button',{name:'验收网站',exact:true}).count()===1,'添加网站成功');
  await page.reload();
  await page.getByRole('button',{name:'验收网站',exact:true}).waitFor();
  assert(await page.getByRole('button',{name:'验收网站',exact:true}).count()===1,'网站刷新后保留');
  await page.getByRole('button',{name:'验收网站',exact:true}).click({button:'right'});
  await page.getByRole('button',{name:'编辑图标',exact:true}).click();
  await page.getByRole('textbox',{name:'名称',exact:true}).fill('验收网站已编辑');
  await page.locator('#site-form').getByRole('button',{name:'保存',exact:true}).click();
  await page.getByRole('button',{name:'验收网站已编辑',exact:true}).waitFor();
  assert(await page.getByRole('button',{name:'验收网站已编辑',exact:true}).count()===1,'网站编辑成功');
  await page.getByRole('button',{name:'验收网站已编辑',exact:true}).dragTo(page.getByRole('button',{name:'天气',exact:true}));
  assert(await page.locator('#grid article').first().getAttribute('aria-label')===null&&await page.locator('#grid article').first().locator('.item-label').textContent()==='验收网站已编辑','拖拽可调整网格顺序');
  await page.getByRole('button',{name:'备忘录',exact:true}).click();
  await page.getByRole('textbox',{name:'备忘录内容'}).fill('浏览器验收\n自动保存测试');
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'备忘录',exact:true}).click();
  assert((await page.getByRole('textbox',{name:'备忘录内容'}).inputValue()).includes('自动保存测试'),'便签自动保存并持久化');
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('button',{name:'切换极简模式',exact:true}).click();
  assert(!(await page.locator('#desktop').isVisible()),'极简模式隐藏图标');
  await page.getByRole('button',{name:'切换极简模式',exact:true}).click();
  assert(await page.locator('#desktop').isVisible(),'点击时间恢复组件布局');
  assert(errors.length===0,'主要流程无未捕获的 JavaScript 错误');
  return {checks,metrics,errors};
}
